name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nima:
    path: ../dependencies/Nima-Flutter
  flare_flutter:
    path: ../dependencies/Flare-Flutter/flare_flutter
  flutter_markdown: ^0.5.0
  share: ^0.6.5+4
  intl: ">=0.14.0"
  shared_preferences: ^0.5.12+4
  rxdart: ^0.25.0
  url_launcher: ^5.7.10


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
      - family: RobotoMedium
        fonts:
          - asset: assets/fonts/Roboto-Medium.ttf
    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/Articles/
    - assets/Big_Bang/
    - assets/Milky Way/
    - assets/Mammals/
    - assets/Dinosaurs/
    - assets/Insects/
    - assets/Fish_and_Stuff/
    - assets/Cells/
    - assets/Dinosaur_Demise/
    - assets/Reptiles/
    - assets/World_War_I/
    - assets/Moon/
    - assets/Newton/
    - assets/Cold_war/
    - assets/Crusades/
    - assets/Homo_Sapiens_Sapiens/
    - assets/Nelson Mandela_v2/
    - assets/Martin Luther king/
    - assets/Sufraggette_movement/
    - assets/Marie_Curie/
    - assets/Amelia_Earhart/
    - assets/Alan_Turing/
    - assets/World_War_II/
    - assets/Darwin 2/
    - assets/Internet/
    - assets/Agricultural_evolution/
    - assets/Writing/
    - assets/Recorded_history/
    - assets/Pyramid/
    - assets/Roma/
    - assets/Industrialization/
    - assets/Constantinople/
    - assets/BlackPlague/
    - assets/First_Temple/
    - assets/Apes/
    - assets/Constructive_Tools/
    - assets/Fire/